schema_version = "1.0.0"

id = "aspect_ratio"
name = "Advanced Aspect Ratio"
version = "1.4.0"
tagline = "Advanced aspect ratio manager with camera overlay and composition guides"
type = "add-on"
maintainer = "Dimona Patrick <dream.pixels.forge@gmail.com>"
website = "https://github.com/Dream-Pixels-Forge/aspect_ratio"
tags = ["Render", "Object"]
blender_version_min = "4.5.0"
blender_version_max = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025, Dimona Patrick, Dream-Pixels-Forge"]

[permissions]
